//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Coffee.cpp
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#include "Coffee.h"

void Coffee::GetType() {

}

