//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CoffeeTypes.h
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#if !defined(_COFFEETYPES_H)
#define _COFFEETYPES_H


enum CoffeeTypes {
	granular,
	ground,
	instant
};

#endif  //_COFFEETYPES_H
