//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.h
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#if !defined(_PRODUCT_H)
#define _PRODUCT_H
#include <string>;
using namespace std;

class Product {
private:
	string name;
	int price;
	int weight;

public:
	Product(string name, int price, int weight) {
		this->name = name;
		this->price = price;
		this->weight = weight;
	}

	virtual void Show() {
		std::cout << name << " " << price << " " << weight;
	}

    void setName(string product_name) {
        name = product_name;
    }

	string getName() {
		return name;
	}

    void setPrice(int product_price) {
        price = product_price;
    }

	int getPrice() {
		return price;
	}

    void setWeight(int product_weight) {
        weight = product_weight;
    }

	int getWeight() {
		return weight;
	}

};



#endif  //_PRODUCT_H
