//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.h
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#if !defined(_PRODUCT_H)
#define _PRODUCT_H
#include <string>;

class Product {
private:
	string name;
	int price;
	int weight;

public:
	Product(string name, int price, weight) {
		this->name = name;
		this->price = price;
		this->weight = weight;
	}

	void Show() {
		std::cout << name << " " << price << " " << weight;
	}

	void getName() {
		return name;
	}

	void getPrice() {
		return price;
	}

	void getWeight() {
		return weight;
	}

};



#endif  //_PRODUCT_H
