//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tea.cpp
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#include "Tea.h"

void Tea::GetType() {

}

