//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TeaTypes.h
//  @ Date : 23.02.2018
//  @ Author : 
//
//


#if !defined(_TEATYPES_H)
#define _TEATYPES_H


enum TeaTypes {
	green,
	black
};

#endif  //_TEATYPES_H
